name: ci for go app
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      
      - uses: actions/checkout@v6

      
      - name: setup go
        uses: actions/setup-go@v6
        with: 
            go-verion: '1.23'

      - name: test the go app
        run: go test -v 

      - name: build the app
        run: go build -o app main.go
      

    
  
